---
name: Run tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
        perl-version: 
          - '5.22'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh $HOME/.local
      - name: Run tests
        run: |
          PATH="$HOME/.local/bin:$PATH"
          bats --tap test/test.bats
